/**
 * Development seed recipes – original texts written for this project (not copied
 * from any recipe site). They make the app usable immediately; ingredient lines
 * go through the same parser + matcher as imported recipes.
 */
import type { MatchContext } from '../domain/matcher'
import { buildIngredientList } from '../domain/recipeIngredients'
import type { Recipe } from '../domain/types'

interface SeedRecipe {
  id: string
  title: string
  description: string
  servings: number
  prepTimeMin?: number
  cookTimeMin?: number
  tags: string[]
  category: string
  ingredients: string[]
  instructions: string[]
}

export const SEED_VERSION = 1

export const SEED_RECIPES: SeedRecipe[] = [
  {
    id: 'seed-kaurapuuro',
    title: 'Kaurapuuro marjoilla',
    description: 'Arkiaamun perusaamiainen: kermainen kaurapuuro, marjoja ja ripaus kanelia.',
    servings: 2,
    prepTimeMin: 2,
    cookTimeMin: 8,
    tags: ['aamiainen', 'kasvis', 'nopea'],
    category: 'Aamiainen',
    ingredients: ['2 dl kaurahiutaleita', '4 dl vettä', '1 dl kevytmaitoa', '¼ tl suolaa', '2 dl mustikoita', '½ tl kanelia'],
    instructions: [
      'Kiehauta vesi ja suola kattilassa.',
      'Lisää kaurahiutaleet ja keitä miedolla lämmöllä sekoitellen noin 5 minuuttia.',
      'Sekoita joukkoon maito ja kuumenna vielä hetki.',
      'Tarjoa marjojen ja kanelin kanssa.',
    ],
  },
  {
    id: 'seed-munakas',
    title: 'Kasvismunakas',
    description: 'Pannulla paistettu munakas paprikalla, pinaatilla ja juustolla.',
    servings: 2,
    prepTimeMin: 5,
    cookTimeMin: 10,
    tags: ['aamiainen', 'kasvis', 'nopea', 'runsasproteiininen'],
    category: 'Aamiainen',
    ingredients: [
      '5 kananmunaa',
      '1 dl kevytmaitoa',
      '½ tl suolaa',
      '1 paprika',
      '50 g pinaattia',
      '1 dl juustoraastetta',
      '1 rkl rypsiöljyä',
      'mustapippuria',
    ],
    instructions: [
      'Vatkaa munat, maito ja suola kulhossa.',
      'Kuutioi paprika ja kuullota sitä öljyssä pannulla muutama minuutti.',
      'Lisää pinaatti ja anna sen pehmetä.',
      'Kaada munaseos pannulle ja paista miedolla lämmöllä, kunnes pinta hyytyy.',
      'Ripottele pinnalle juustoraaste, taita munakas ja mausta pippurilla.',
    ],
  },
  {
    id: 'seed-rahka',
    title: 'Marjarahka',
    description: 'Proteiinipitoinen välipala rahkasta, jogurtista ja marjoista.',
    servings: 2,
    prepTimeMin: 5,
    tags: ['välipala', 'kasvis', 'nopea', 'runsasproteiininen'],
    category: 'Välipala',
    ingredients: ['250 g maitorahkaa', '2 dl maustamatonta jogurttia', '2 dl pakastemarjoja', '1 rkl hunajaa'],
    instructions: ['Sulata marjat osittain.', 'Sekoita rahka ja jogurtti tasaiseksi.', 'Lisää marjat ja hunaja ja sekoita kevyesti.'],
  },
  {
    id: 'seed-lohikeitto',
    title: 'Kermainen lohikeitto',
    description: 'Klassinen suomalainen lohikeitto perunoilla, purjolla ja tillillä.',
    servings: 4,
    prepTimeMin: 15,
    cookTimeMin: 25,
    tags: ['keitto', 'kala', 'suomalainen', 'arkiruoka'],
    category: 'Pääruoat',
    ingredients: [
      '600 g perunoita',
      '1 purjo',
      '1 porkkana',
      '1 l vettä',
      '1 kalaliemikuutio',
      '400 g lohifileetä',
      '2 dl ruoanvalmistuskermaa',
      '1 tl suolaa',
      '5 maustepippuria',
      '1 ruukku tilliä',
    ],
    instructions: [
      'Kuori ja kuutioi perunat ja porkkana. Leikkaa purjo renkaiksi.',
      'Kiehauta vesi, liemikuutio ja maustepippurit. Lisää perunat ja porkkana ja keitä 10 minuuttia.',
      'Lisää purjo ja paloiteltu lohi. Keitä hiljalleen, kunnes kala on kypsää, noin 5 minuuttia.',
      'Lisää kerma, kuumenna ja tarkista suola. Viimeistele silputulla tillillä.',
    ],
  },
  {
    id: 'seed-jauhelihakeitto',
    title: 'Jauhelihakeitto',
    description: 'Täyttävä arkikeitto jauhelihasta ja juureksista.',
    servings: 4,
    prepTimeMin: 15,
    cookTimeMin: 30,
    tags: ['keitto', 'liha', 'suomalainen', 'arkiruoka'],
    category: 'Pääruoat',
    ingredients: [
      '400 g naudan jauhelihaa',
      '1 sipuli',
      '500 g perunoita',
      '2 porkkanaa',
      '1,2 l vettä',
      '1 lihaliemikuutio',
      '1 tl suolaa',
      '½ tl mustapippuria',
      '2 laakerinlehteä',
      '1 rkl rypsiöljyä',
    ],
    instructions: [
      'Ruskista jauheliha ja hienonnettu sipuli öljyssä kattilassa.',
      'Lisää vesi, liemikuutio ja mausteet ja kiehauta.',
      'Lisää kuutioidut perunat ja porkkanat ja keitä kannen alla noin 20 minuuttia.',
      'Tarkista maku ennen tarjoamista.',
    ],
  },
  {
    id: 'seed-kanapasta',
    title: 'Kermainen kanapasta',
    description: 'Nopea pasta broilerin fileesuikaleista, tomaatista ja pinaatista.',
    servings: 4,
    prepTimeMin: 10,
    cookTimeMin: 20,
    tags: ['pasta', 'broileri', 'arkiruoka', 'runsasproteiininen'],
    category: 'Pääruoat',
    ingredients: [
      '400 g täysjyväspagettia',
      '400 g broilerin fileesuikaleita',
      '1 sipuli',
      '2 valkosipulinkynttä',
      '2 rkl oliiviöljyä',
      '1 prk ruoanvalmistuskermaa',
      '250 g kirsikkatomaatteja',
      '65 g babypinaattia',
      '½ dl parmesaaniraastetta',
      '1 tl suolaa',
      'mustapippuria',
    ],
    instructions: [
      'Keitä pasta pakkauksen ohjeen mukaan.',
      'Kuullota hienonnettu sipuli ja valkosipuli öljyssä. Lisää fileesuikaleet ja paista kypsiksi.',
      'Lisää kerma ja puolitetut tomaatit ja hauduta muutama minuutti. Mausta.',
      'Sekoita joukkoon pinaatti ja pasta. Tarjoa parmesaanin kanssa.',
    ],
  },
  {
    id: 'seed-kasviswokki',
    title: 'Broileri-kasviswokki',
    description: 'Rapeat kasvikset, broileri ja riisi soija-inkiväärikastikkeessa.',
    servings: 4,
    prepTimeMin: 15,
    cookTimeMin: 15,
    tags: ['wokki', 'broileri', 'aasialainen', 'runsasproteiininen'],
    category: 'Pääruoat',
    ingredients: [
      '3 dl riisiä',
      '500 g broilerin fileesuikaleita',
      '400 g wokkivihanneksia',
      '1 paprika',
      '2 rkl rypsiöljyä',
      '3 rkl soijakastiketta',
      '1 rkl raastettua inkivääriä',
      '2 valkosipulinkynttä',
      '1 rkl makeaa chilikastiketta',
    ],
    instructions: [
      'Keitä riisi.',
      'Paista fileesuikaleet kuumassa öljyssä wokkipannulla kypsiksi ja nosta sivuun.',
      'Paista vihannekset ja suikaloitu paprika rapeiksi.',
      'Lisää broileri, soija, inkivääri, valkosipuli ja chilikastike. Kuumenna ja tarjoa riisin kanssa.',
    ],
  },
  {
    id: 'seed-linssikeitto',
    title: 'Punainen linssikeitto',
    description: 'Vegaaninen, mausteinen linssikeitto tomaatilla ja kookosmaidolla.',
    servings: 4,
    prepTimeMin: 10,
    cookTimeMin: 25,
    tags: ['keitto', 'vegaaninen', 'kasvis', 'palkokasvit'],
    category: 'Pääruoat',
    ingredients: [
      '2 dl punaisia linssejä',
      '1 sipuli',
      '2 porkkanaa',
      '2 valkosipulinkynttä',
      '1 rkl oliiviöljyä',
      '1 tlk (400 g) tomaattimurskaa',
      '1 tlk (400 ml) kookosmaitoa',
      '8 dl vettä',
      '1 kasvisliemikuutio',
      '2 tl currya',
      '1 tl juustokuminaa',
      '1 tl suolaa',
      '1 limetti',
    ],
    instructions: [
      'Kuullota hienonnettu sipuli, valkosipuli ja raastettu porkkana öljyssä.',
      'Lisää mausteet ja paahda hetki.',
      'Lisää huuhdotut linssit, tomaattimurska, vesi ja liemikuutio. Keitä noin 20 minuuttia.',
      'Lisää kookosmaito ja soseuta halutessasi. Mausta limetin mehulla ja suolalla.',
    ],
  },
  {
    id: 'seed-kikhernecurry',
    title: 'Kikherne-pinaattikurry',
    description: 'Vegaaninen kurry kikherneistä, bataatista ja pinaatista.',
    servings: 4,
    prepTimeMin: 15,
    cookTimeMin: 25,
    tags: ['kurry', 'vegaaninen', 'kasvis', 'palkokasvit'],
    category: 'Pääruoat',
    ingredients: [
      '2 tlk (à 240 g) kikherneitä',
      '1 bataatti',
      '1 sipuli',
      '2 valkosipulinkynttä',
      '1 rkl currytahnaa',
      '1 tlk (400 ml) kookosmaitoa',
      '1 tlk (400 g) tomaattimurskaa',
      '100 g pinaattia',
      '1 rkl rypsiöljyä',
      '1 tl suolaa',
      '3 dl riisiä',
    ],
    instructions: [
      'Keitä riisi.',
      'Kuullota sipuli ja valkosipuli öljyssä, lisää currytahna.',
      'Lisää kuutioitu bataatti, tomaattimurska ja kookosmaito. Hauduta 15 minuuttia.',
      'Lisää valutetut kikherneet ja pinaatti ja kuumenna. Tarjoa riisin kanssa.',
    ],
  },
  {
    id: 'seed-makaronilaatikko',
    title: 'Makaronilaatikko',
    description: 'Suomalainen uuniruokaklassikko jauhelihasta ja makaronista.',
    servings: 6,
    prepTimeMin: 15,
    cookTimeMin: 60,
    tags: ['uuniruoka', 'liha', 'suomalainen', 'arkiruoka'],
    category: 'Pääruoat',
    ingredients: [
      '400 g makaronia',
      '400 g jauhelihaa',
      '1 sipuli',
      '3 kananmunaa',
      '7 dl kevytmaitoa',
      '1 ½ tl suolaa',
      '½ tl mustapippuria',
      '1 dl juustoraastetta',
      '1 rkl voita',
    ],
    instructions: [
      'Keitä makaronit napakoiksi ja valuta.',
      'Ruskista jauheliha ja sipuli pannulla. Mausta.',
      'Sekoita makaronit ja jauheliha voideltuun vuokaan.',
      'Vatkaa munat, maito ja suola ja kaada vuokaan. Ripottele pinnalle juustoraaste.',
      'Paista 175 asteessa noin tunti, kunnes pinta on kullanruskea.',
    ],
  },
  {
    id: 'seed-uunilohi',
    title: 'Uunilohi ja lohkoperunat',
    description: 'Helppo uunipelti: lohi, perunat ja parsakaali samalla kertaa.',
    servings: 4,
    prepTimeMin: 10,
    cookTimeMin: 35,
    tags: ['uuniruoka', 'kala', 'gluteeniton'],
    category: 'Pääruoat',
    ingredients: [
      '800 g perunoita',
      '500 g lohifileetä',
      '1 parsakaali',
      '3 rkl oliiviöljyä',
      '1 sitruuna',
      '1 tl suolaa',
      '½ tl mustapippuria',
      '1 dl kermaviiliä',
      '½ ruukkua tilliä',
    ],
    instructions: [
      'Lohko perunat, sekoita puoleen öljystä ja suolaan ja paista 225 asteessa 15 minuuttia.',
      'Lisää pellille lohi ja parsakaalin kukinnot. Valuta pinnalle loput öljystä ja sitruunan mehu.',
      'Paista vielä 15–20 minuuttia, kunnes lohi on kypsää.',
      'Tarjoa tillillä maustetun kermaviilikastikkeen kanssa.',
    ],
  },
  {
    id: 'seed-tortillat',
    title: 'Jauheliha-tortillat',
    description: 'Perheen perjantairuoka: mausteinen jauheliha, kasvikset ja salsa tortillassa.',
    servings: 4,
    prepTimeMin: 15,
    cookTimeMin: 15,
    tags: ['texmex', 'liha', 'viikonloppu'],
    category: 'Pääruoat',
    ingredients: [
      '400 g naudan jauhelihaa',
      '1 pkt tacomaustetta',
      '1 dl vettä',
      '8 vehnätortillaa',
      '½ kerää jäävuorisalaattia',
      '2 tomaattia',
      '1 kurkku',
      '1 prk (230 g) tacokastiketta',
      '2 dl kermaviiliä',
      '1,5 dl juustoraastetta',
      '1 tlk (285 g) maissia',
    ],
    instructions: [
      'Ruskista jauheliha pannulla, lisää tacomauste ja vesi ja hauduta 5 minuuttia.',
      'Pilko salaatti, tomaatit ja kurkku.',
      'Lämmitä tortillat.',
      'Kokoa tortillat täytteistä ja kastikkeista oman maun mukaan.',
    ],
  },
  {
    id: 'seed-kreikkalainen-salaatti',
    title: 'Kreikkalainen salaatti',
    description: 'Raikas salaatti fetajuustosta, oliiveista ja kasviksista.',
    servings: 4,
    prepTimeMin: 15,
    tags: ['salaatti', 'kasvis', 'nopea', 'gluteeniton'],
    category: 'Salaatit',
    ingredients: [
      '1 kurkku',
      '4 tomaattia',
      '1 punasipuli',
      '1 paprika',
      '200 g fetajuustoa',
      '1 dl kalamata-oliiveja',
      '3 rkl oliiviöljyä',
      '1 rkl punaviinietikkaa',
      '1 tl kuivattua oreganoa',
    ],
    instructions: [
      'Pilko kasvikset reiluiksi paloiksi ja sipuli ohuiksi renkaiksi.',
      'Kokoa kulhoon ja lisää oliivit ja paloiteltu feta.',
      'Sekoita öljy, etikka ja oregano ja valuta salaatin päälle.',
    ],
  },
  {
    id: 'seed-kasvislasagne',
    title: 'Kasvislasagne härkäpapurouheella',
    description: 'Kasvisproteiinilla ja pinaatilla täytetty lasagne.',
    servings: 6,
    prepTimeMin: 25,
    cookTimeMin: 50,
    tags: ['uuniruoka', 'kasvis', 'pasta'],
    category: 'Pääruoat',
    ingredients: [
      'Kastike:',
      '250 g kasviproteiinirouhetta',
      '1 sipuli',
      '2 valkosipulinkynttä',
      '2 rkl oliiviöljyä',
      '2 tlk (à 400 g) tomaattimurskaa',
      '1 tl oreganoa',
      '1 tl suolaa',
      'Juustokastike:',
      '3 rkl voita',
      '½ dl vehnäjauhoja',
      '6 dl kevytmaitoa',
      '½ tl suolaa',
      '150 g pakastepinaattia',
      'Lisäksi:',
      '12 lasagnelevyä',
      '150 g mozzarellaraastetta',
    ],
    instructions: [
      'Kuullota sipuli ja valkosipuli öljyssä, lisää rouhe ja tomaattimurska. Mausta ja hauduta 10 minuuttia.',
      'Sulata voi, lisää jauhot ja vähitellen maito. Keitä sakeaksi, lisää pinaatti ja suola.',
      'Lado vuokaan kerroksittain kastiketta, levyjä ja juustokastiketta.',
      'Ripottele pinnalle juusto ja paista 200 asteessa noin 40 minuuttia.',
    ],
  },
  {
    id: 'seed-ruisleipa-kananmuna',
    title: 'Ruisleipä ja kananmuna',
    description: 'Yksinkertainen suomalainen aamupala tai välipala.',
    servings: 1,
    prepTimeMin: 10,
    tags: ['aamiainen', 'kasvis', 'nopea', 'suomalainen'],
    category: 'Aamiainen',
    ingredients: ['2 viipaletta ruisleipää', '1 tl margariinia', '2 kananmunaa', '½ tomaattia', '½ kurkku'],
    instructions: ['Keitä kananmunia 8 minuuttia ja jäähdytä kylmässä vedessä.', 'Levitä leivälle margariinia.', 'Tarjoa viipaloitujen munien ja kasvisten kanssa.'],
  },
]

export function buildSeedRecipes(ctx: MatchContext, now = new Date().toISOString()): Recipe[] {
  return SEED_RECIPES.map((s) => ({
    id: s.id,
    title: s.title,
    description: s.description,
    servings: s.servings,
    servingsText: `${s.servings} annosta`,
    prepTimeMin: s.prepTimeMin ?? null,
    cookTimeMin: s.cookTimeMin ?? null,
    totalTimeMin: (s.prepTimeMin ?? 0) + (s.cookTimeMin ?? 0) || null,
    timeText: null,
    imageUrl: null,
    ingredients: buildIngredientList(s.ingredients, ctx),
    instructions: s.instructions,
    tags: s.tags,
    category: s.category,
    cuisine: null,
    origin: 'seed',
    sourceId: 'user',
    sourceUrl: null,
    sourceName: 'Ateriasuunnittelijan esimerkkiresepti',
    author: null,
    sourceNutrition: null,
    importReport: null,
    inCollection: true,
    createdAt: now,
    updatedAt: now,
  }))
}
